### ISSUE TITLE
[PE-D][Tester A] Error in user guide. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-2/tp#85]
![image.png](https://raw.githubusercontent.com/JingHaoooo/ped/main/files/18809bec-816e-4e11-8c64-a0363774316c.png)

Is the feature trying to add a new todo or is it trying to change the task type?

-------------
Labels: `type.DocumentationBug` `severity.High`
original: JingHaoooo/ped#3

**Comment by john-nng** [comment]
Removed todo from UG.
